development:
  adapter: postgresql
  encoding: unicode
  database: myblogapp_development
  pool: 5
  host: localhost
  username: postgres
  password: 3009

test:
  adapter: postgresql
  encoding: unicode
  database: myblogapp_test
  pool: 5
  username: postgres
  password: 3009

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 