development:
  adapter: postgresql
  encoding: unicode
  database: MyBlogApp_development
  pool: 5
  host: localhost
  username: postgres
  password: <%= ENV["MYBLOGAPP_DATABASE_PASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: MyBlogApp_test
  pool: 5
  username: postgres
  password: <%= ENV["MYBLOGAPP_DATABASE_PASSWORD"] %>

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 